import {Painting} from './app/models/painting';

export const PAINTINGS: Painting[] = [
  new Painting(
    0,
    'Rolien Schrik',
    'Polly',
    'Phasellus ultricies, nisi vitae rutrum hendrerit, justo nunc faucibus libero, vel suscipit nibh erat id arcu. Cras ac vehicula diam. Nullam molestie vehicula ipsum a consequat. Vivamus efficitur metus ut nulla consectetur porta. Proin auctor dui ut orci aliquet, sit amet ultricies justo mattis. Mauris nec massa sit amet metus dignissim placerat elementum a justo. Nunc sit amet facilisis velit, ac varius enim.',
    '/assets/img/polly.jpg',
    'Oil',
    'Hout',
    'Niet Beschikbaar',
    250,
    'TV Series',
    '100 x 200',
    Date.now(),
    null,
  ),
  new Painting(
    1,
    'Rolien Schrik',
    'Highland Cow',
    'Phasellus ultricies, nisi vitae rutrum hendrerit, justo nunc faucibus libero, vel suscipit nibh erat id arcu. Cras ac vehicula diam. Nullam molestie vehicula ipsum a consequat. Vivamus efficitur metus ut nulla consectetur porta. Proin auctor dui ut orci aliquet, sit amet ultricies justo mattis. Mauris nec massa sit amet metus dignissim placerat elementum a justo. Nunc sit amet facilisis velit, ac varius enim.',
    '/assets/img/hooglander.jpg',
    'Oil',
    'Hout',
    'Opdrachten',
    500,
    'Animals',
    '100 x 200',
    Date.now(),
    null,
  ),
  new Painting(
    5,
    'Rolien Schrik',
    'Tommy',
    'Phasellus ultricies, nisi vitae rutrum hendrerit, justo nunc faucibus libero, vel suscipit nibh erat id arcu. Cras ac vehicula diam. Nullam molestie vehicula ipsum a consequat. Vivamus efficitur metus ut nulla consectetur porta. Proin auctor dui ut orci aliquet, sit amet ultricies justo mattis. Mauris nec massa sit amet metus dignissim placerat elementum a justo. Nunc sit amet facilisis velit, ac varius enim.',
    '/assets/img/tommy.jpg',
    'Acryl',
    'Hout',
    'Opdrachten',
    850,
    'TV Series',
    '100 x 200',
    Date.now(),
    null,
  ),
  new Painting(
    7,
    'Rolien Schrik',
    'Tommy horse',
    'Phasellus ultricies, nisi vitae rutrum hendrerit, justo nunc faucibus libero, vel suscipit nibh erat id arcu. Cras ac vehicula diam. Nullam molestie vehicula ipsum a consequat. Vivamus efficitur metus ut nulla consectetur porta. Proin auctor dui ut orci aliquet, sit amet ultricies justo mattis. Mauris nec massa sit amet metus dignissim placerat elementum a justo. Nunc sit amet facilisis velit, ac varius enim.',
    '/assets/img/tommyhorse.jpg',
    'Acryl',
    'Doek',
    'Beschikbaar',
    550,
    'TV Series',
    '100 x 200',
    Date.now(),
    null,
  ),
  new Painting(
    8,
    'Rolien Schrik',
    'Dessert car',
    'Phasellus ultricies, nisi vitae rutrum hendrerit, justo nunc faucibus libero, vel suscipit nibh erat id arcu. Cras ac vehicula diam. Nullam molestie vehicula ipsum a consequat. Vivamus efficitur metus ut nulla consectetur porta. Proin auctor dui ut orci aliquet, sit amet ultricies justo mattis. Mauris nec massa sit amet metus dignissim placerat elementum a justo. Nunc sit amet facilisis velit, ac varius enim.',
    '/assets/img/dessertcar.jpg',
    'Oil',
    'Doek',
    'Niet Beschikbaar',
    250,
    'Car',
    '100 x 200',
    Date.now(),
    null,
  ),
  new Painting(
    9,
    'Rolien Schrik',
    'Elephant',
    'Phasellus ultricies, nisi vitae rutrum hendrerit, justo nunc faucibus libero, vel suscipit nibh erat id arcu. Cras ac vehicula diam. Nullam molestie vehicula ipsum a consequat. Vivamus efficitur metus ut nulla consectetur porta. Proin auctor dui ut orci aliquet, sit amet ultricies justo mattis. Mauris nec massa sit amet metus dignissim placerat elementum a justo. Nunc sit amet facilisis velit, ac varius enim.',
    '/assets/img/elephant.jpg',
    'Water',
    'Doek',
    'Beschikbaar',
    250,
    'Nature',
    '100 x 200',
    Date.now(),
    null,
  ),
];
