import {Painting} from './app/models/painting';

export const PAINTINGS: Painting[] = [
  new Painting(
    0,
    'Rolien Schrik',
    'Polly from Peaky Blinders',
    'Phasellus ultricies, nisi vitae rutrum hendrerit, justo nunc faucibus libero, vel suscipit nibh erat id arcu. Cras ac vehicula diam. Nullam molestie vehicula ipsum a consequat. Vivamus efficitur metus ut nulla consectetur porta. Proin auctor dui ut orci aliquet, sit amet ultricies justo mattis. Mauris nec massa sit amet metus dignissim placerat elementum a justo. Nunc sit amet facilisis velit, ac varius enim.',
    '/assets/img/polly.jpg',
    'Oil',
    'Sold',
    250,
    'TV Series',
    Date.now(),
    null,
  ),
  new Painting(
    1,
    'Rolien Schrik',
    'Highland Cow',
    'Phasellus ultricies, nisi vitae rutrum hendrerit, justo nunc faucibus libero, vel suscipit nibh erat id arcu. Cras ac vehicula diam. Nullam molestie vehicula ipsum a consequat. Vivamus efficitur metus ut nulla consectetur porta. Proin auctor dui ut orci aliquet, sit amet ultricies justo mattis. Mauris nec massa sit amet metus dignissim placerat elementum a justo. Nunc sit amet facilisis velit, ac varius enim.',
    '/assets/img/hooglander.jpg',
    'Oil',
    'Sold',
    500,
    'Animals',
    Date.now(),
    null,
  ),
  new Painting(
    5,
    'Rolien Schrik',
    'Tommy from Peaky Blinders',
    'Phasellus ultricies, nisi vitae rutrum hendrerit, justo nunc faucibus libero, vel suscipit nibh erat id arcu. Cras ac vehicula diam. Nullam molestie vehicula ipsum a consequat. Vivamus efficitur metus ut nulla consectetur porta. Proin auctor dui ut orci aliquet, sit amet ultricies justo mattis. Mauris nec massa sit amet metus dignissim placerat elementum a justo. Nunc sit amet facilisis velit, ac varius enim.',
    '/assets/img/tommy.jpg',
    'Acryl',
    'For Sale',
    850,
    'TV Series',
    Date.now(),
    null,
  ),
  new Painting(
    7,
    'Rolien Schrik',
    'Tommy on a horse from Peaky Blinders',
    'Phasellus ultricies, nisi vitae rutrum hendrerit, justo nunc faucibus libero, vel suscipit nibh erat id arcu. Cras ac vehicula diam. Nullam molestie vehicula ipsum a consequat. Vivamus efficitur metus ut nulla consectetur porta. Proin auctor dui ut orci aliquet, sit amet ultricies justo mattis. Mauris nec massa sit amet metus dignissim placerat elementum a justo. Nunc sit amet facilisis velit, ac varius enim.',
    '/assets/img/tommyhorse.jpg',
    'Acryl',
    'For Sale',
    550,
    'TV Series',
    Date.now(),
    null,
  ),
  new Painting(
    8,
    'Rolien Schrik',
    'Car in the Desert',
    'Phasellus ultricies, nisi vitae rutrum hendrerit, justo nunc faucibus libero, vel suscipit nibh erat id arcu. Cras ac vehicula diam. Nullam molestie vehicula ipsum a consequat. Vivamus efficitur metus ut nulla consectetur porta. Proin auctor dui ut orci aliquet, sit amet ultricies justo mattis. Mauris nec massa sit amet metus dignissim placerat elementum a justo. Nunc sit amet facilisis velit, ac varius enim.',
    '/assets/img/dessertcar.jpg',
    'Oil',
    'Sold',
    250,
    'Car',
    Date.now(),
    null,
  ),
  new Painting(
    9,
    'Rolien Schrik',
    'Elephant',
    'Phasellus ultricies, nisi vitae rutrum hendrerit, justo nunc faucibus libero, vel suscipit nibh erat id arcu. Cras ac vehicula diam. Nullam molestie vehicula ipsum a consequat. Vivamus efficitur metus ut nulla consectetur porta. Proin auctor dui ut orci aliquet, sit amet ultricies justo mattis. Mauris nec massa sit amet metus dignissim placerat elementum a justo. Nunc sit amet facilisis velit, ac varius enim.',
    '/assets/img/elephant.jpg',
    'Water',
    'For Sale',
    250,
    'Nature',
    Date.now(),
    null,
  ),
];
